version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/compact-js"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/platform-js"
    schedule:
      interval: "weekly"
